# name (REQUIRED) - not used much, only for the docker image name
name = "tpl"
# config version (REQUIRED)
version = "1"


# package manager command for installing packages (apk is default)
install = "apk add"
# package manager command for updating a package manager repository (apk is default)
update = "apk update"
# packages to install (according to the package manager)
packages = [ "texlive", "make", "biblatex", "biber", "texmf-dist-bibtexextra", "texmf-dist-latexextra" ]


# The three possibilities below are mutually exclusive. (REQUIRED)
[inherit]
docker = "pandoc/core:latest"

[project.files]
"essay/src" = "src"
"essay/.gitignore" = ".gitignore"
"essay/essay.bib" = "essay.bib"
"essay/essay.tex" = "essay.tex"
"essay/Makefile" = "Makefile"


[project.commands]
compile = "make clean all"