name = "template-math"
version = "1"

#update = "apk update"
install = "apk add"
packages = [
  "texlive",
  "make",
  "texmf-dist-latexextra",
  "texmf-dist-fontsextra",
  "texmf-dist-science",
  "texmf-dist-pictures",
  "python3", "py3-numpy", "py3-scipy", "py3-pygments"
]

# The three possibilities below are mutually exclusive. (REQUIRED)
[inherit]
docker = "alpine:latest"

[project.files]
"math/main.tex" = "main.tex"
"math/juni.cls" = "juni.cls"
"math/Makefile" = "Makefile"
"math/.gitignore" = ".gitignore"

# commands for the project (invoked with `texbld run $COMMAND`)
[project.commands]
"compile" = "make clean all"
"watch" = "make watch"
"clean" = "make clean"
